### ISSUE TITLE
macOS: build warnings and error

### ISSUE THREAD

**Issue by grylem** [dcantrell/bsdutils#2]
too many warnings and
./compat.h:20:29: error: expected identifier
char *group_from_gid(gid_t, int);
Thanks.

**Comment by dcantrell** [comment]
I suspect with MacOS X, the issue is going to be different header files.  However, MacOS X already provides BSD variants of these commands.  Linux is what I am targeting, so my patches and modifications are aimed at a Linux glibc platform.

Nonetheless, I am not opposed to making this work on MacOS X.  I don't have one of those systems, so I can't do much without more debugging output or access to a MacOS X system.

**Comment by grylem** [comment]
>MacOS X already provides BSD variants of these commands.

Yes i known

>Nonetheless, I am not opposed to making this work on MacOS X. I don't have one of those systems, so I can't do much without more debugging output or access to a MacOS X system.

I understand. Anyway thanks.
